### ISSUE TITLE
./make.sh fail for faster_rcnn

### ISSUE THREAD

**Issue by StrangeTcy** [nexusapoorvacus/DeepVariationStructuredRL#4]
Trying to run `./make.sh` to build the faster rcnn part of the whole model fails with the following error:

> Traceback (most recent call last):
>   File "build.py", line 3, in <module>
>     from torch.utils.ffi import create_extension
>   File "/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/__init__.py", line 1, in <module>
>     raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
> ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

I assume that `build.py` expects an older pytorch (<=0.4) than the one I'm using (1.0).
Is there any way to fix this (provided that, everything else failing, I can always create an environment with pytorch=0.4.0)?

**Comment by StrangeTcy** [comment]
Ok, it worked in an environment with `pytorch==0.4.0`. Still, I wouldn't rely on people using it in the future.
