### ISSUE TITLE
setup.sh expects a non-existent directory

### ISSUE THREAD

**Issue by StrangeTcy** [nexusapoorvacus/DeepVariationStructuredRL#5]
After being run in project root directory, `setup.sh` fails with 

> Traceback (most recent call last):
>   File "create_data_samples.py", line 69, in <module>
>     data = create_data_sample_file()
>   File "create_data_samples.py", line 18, in create_data_sample_file
>     for im_name in os.listdir(IMAGE_DIR)[:NUM_IMAGES_TRAIN + NUM_IMAGES_VALIDATION + NUM_IMAGES_TEST]:
> FileNotFoundError: [Errno 2] No such file or directory: '/data/apoorvad/VG_Scene_Graph/VG_100K/'

This is a directory never mentioned in the `README`, so it wasn't created when following the instructions.

**Comment by 13732858501** [comment]
I have encountered the same problem, have you solved it?

**Comment by nexusapoorvacus** [comment]
Sorry about that, just fixed the path. The correct path is data/VG_100K. You should download the Visual Genome image data as specified in the README directions in data/VG_100K

**Comment by 13732858501** [comment]
Thank you .But I got another error, evaluation  function is not defined when I typed the python main.py --test command.
